spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASS}

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate